sudo: required

services:
  - docker

env:
  # default build
  - DISTRO=alpine-3.5           TEST_PY_OPTS=""
  - DISTRO=alpine-3.6           TEST_PY_OPTS=""
  - DISTRO=alpine-edge          TEST_PY_OPTS=""
  - DISTRO=archlinux            TEST_PY_OPTS=""
  - DISTRO=centos-7             TEST_PY_OPTS=""
  - DISTRO=debian-buster        TEST_PY_OPTS=""
  - DISTRO=debian-jessie        TEST_PY_OPTS=""
  - DISTRO=debian-sid           TEST_PY_OPTS=""
  - DISTRO=debian-stretch       TEST_PY_OPTS=""
  - DISTRO=fedora-25            TEST_PY_OPTS=""
  - DISTRO=fedora-26            TEST_PY_OPTS=""
  - DISTRO=fedora-27            TEST_PY_OPTS=""
  - DISTRO=fedora-rawhide       TEST_PY_OPTS=""
  - DISTRO=opensuse-42.3        TEST_PY_OPTS=""
  - DISTRO=opensuse-tumbleweed  TEST_PY_OPTS=""
  - DISTRO=ubuntu-16.04         TEST_PY_OPTS=""
  - DISTRO=ubuntu-17.04         TEST_PY_OPTS=""
  - DISTRO=ubuntu-17.10         TEST_PY_OPTS=""
  # default cmake build
  - DISTRO=alpine-3.5           TEST_PY_OPTS="--cmake"
  - DISTRO=alpine-3.6           TEST_PY_OPTS="--cmake"
  - DISTRO=alpine-edge          TEST_PY_OPTS="--cmake"
  - DISTRO=archlinux            TEST_PY_OPTS="--cmake"
  - DISTRO=centos-7             TEST_PY_OPTS="--cmake"
  - DISTRO=debian-buster        TEST_PY_OPTS="--cmake"
  - DISTRO=debian-jessie        TEST_PY_OPTS="--cmake"
  - DISTRO=debian-sid           TEST_PY_OPTS="--cmake"
  - DISTRO=debian-stretch       TEST_PY_OPTS="--cmake"
  - DISTRO=fedora-25            TEST_PY_OPTS="--cmake"
  - DISTRO=fedora-26            TEST_PY_OPTS="--cmake"
  - DISTRO=fedora-27            TEST_PY_OPTS="--cmake"
  - DISTRO=fedora-rawhide       TEST_PY_OPTS="--cmake"
  - DISTRO=opensuse-42.3        TEST_PY_OPTS="--cmake"
  - DISTRO=opensuse-tumbleweed  TEST_PY_OPTS="--cmake"
  - DISTRO=ubuntu-16.04         TEST_PY_OPTS="--cmake"
  - DISTRO=ubuntu-17.04         TEST_PY_OPTS="--cmake"
  - DISTRO=ubuntu-17.10         TEST_PY_OPTS="--cmake"
  # scons clang release build
  - DISTRO=alpine-3.5           TEST_PY_OPTS="-- clang.release"
  - DISTRO=alpine-3.6           TEST_PY_OPTS="-- clang.release"
  - DISTRO=alpine-edge          TEST_PY_OPTS="-- clang.release"
  - DISTRO=archlinux            TEST_PY_OPTS="-- clang.release"
  - DISTRO=centos-7             TEST_PY_OPTS="-- clang.release"
  - DISTRO=debian-buster        TEST_PY_OPTS="-- clang.release"
  - DISTRO=debian-jessie        TEST_PY_OPTS="-- clang.release"
  - DISTRO=debian-sid           TEST_PY_OPTS="-- clang.release"
  - DISTRO=debian-stretch       TEST_PY_OPTS="-- clang.release"
  - DISTRO=fedora-25            TEST_PY_OPTS="-- clang.release"
  - DISTRO=fedora-26            TEST_PY_OPTS="-- clang.release"
  - DISTRO=fedora-27            TEST_PY_OPTS="-- clang.release"
  - DISTRO=fedora-rawhide       TEST_PY_OPTS="-- clang.release"
  - DISTRO=opensuse-42.3        TEST_PY_OPTS="-- clang.release"
  - DISTRO=opensuse-tumbleweed  TEST_PY_OPTS="-- clang.release"
  - DISTRO=ubuntu-16.04         TEST_PY_OPTS="-- clang.release"
  - DISTRO=ubuntu-17.04         TEST_PY_OPTS="-- clang.release"
  - DISTRO=ubuntu-17.10         TEST_PY_OPTS="-- clang.release"
  # cmake release build
  - DISTRO=alpine-3.5           TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=alpine-3.6           TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=alpine-edge          TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=archlinux            TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=centos-7             TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=debian-buster        TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=debian-jessie        TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=debian-sid           TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=debian-stretch       TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=fedora-25            TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=fedora-26            TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=fedora-27            TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=fedora-rawhide       TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=opensuse-42.3        TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=opensuse-tumbleweed  TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=ubuntu-16.04         TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=ubuntu-17.04         TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  - DISTRO=ubuntu-17.10         TEST_PY_OPTS="--cmake --target clang.release --dir clang.release"
  # scons clang release nounity ninja build with ASAN
  - DISTRO=alpine-3.5           TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=alpine-3.6           TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=alpine-edge          TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=archlinux            TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=centos-7             TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=debian-buster        TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=debian-jessie        TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=debian-sid           TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=debian-stretch       TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=fedora-25            TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=fedora-26            TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=fedora-27            TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=fedora-rawhide       TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=opensuse-42.3        TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=opensuse-tumbleweed  TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=ubuntu-16.04         TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=ubuntu-17.04         TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  - DISTRO=ubuntu-17.10         TEST_PY_OPTS="-- clang.release.nounity --ninja --sanitize=address"
  # scons gcc static coverage build with TSAN and asserts enabled
  - DISTRO=alpine-3.5           TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=alpine-3.6           TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=alpine-edge          TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=archlinux            TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=centos-7             TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=debian-buster        TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=debian-jessie        TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=debian-sid           TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=debian-stretch       TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=fedora-25            TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=fedora-26            TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=fedora-27            TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=fedora-rawhide       TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=opensuse-42.3        TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=opensuse-tumbleweed  TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=ubuntu-16.04         TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=ubuntu-17.04         TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"
  - DISTRO=ubuntu-17.10         TEST_PY_OPTS="-- gcc.coverage --static --assert --sanitize=thread"

before_install:
  - cd $DISTRO
  # --no-cache might not be necessary
  # - docker build --no-cache -t rippled/$DISTRO .
  - docker build -t rippled/$DISTRO .

script:
  - docker run --rm -t rippled/$DISTRO /bin/bash -c "cd .. && num_procs=$(lscpu -p | grep -v '^#' | sort -u -t, -k 2,4 | wc -l) ./Builds/Test.py $TEST_PY_OPTS -- -j$num_procs"
  # This takes FAR too long for Travis-ci:
  # - docker run --rm -t rippled/$DISTRO /bin/bash -c "./build_all.sh"
